# Generated by Django 4.2.13 on 2024-07-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filter", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="books",
            name="isbn",
        ),
        migrations.AddField(
            model_name="books",
            name="price",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
