# Generated by Django 4.2.13 on 2024-07-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signals_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="students", to="signals_app.course"
                    ),
                ),
            ],
        ),
    ]
