# Generated by Django 4.2.13 on 2024-07-12 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_product_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="name",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="price",
        ),
        migrations.AddField(
            model_name="orders",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.product",
            ),
            preserve_default=False,
        ),
    ]
