# Generated by Django 4.2.13 on 2024-07-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="date",
            new_name="ordered_date",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="address",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="phone",
        ),
    ]
