# Generated by Django 4.2.13 on 2024-07-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_rename_date_orders_ordered_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="ordered_date",
            new_name="created_at",
        ),
    ]
