# Generated by Django 4.2.13 on 2024-07-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_rename_ordered_date_orders_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="payment",
            field=models.CharField(
                choices=[("cod", "Cash on Delivery"), ("u", "Upi"), ("c", "Card")],
                default="cod",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[
                    ("p", "Pending"),
                    ("c", "Completed"),
                    ("d", "Delivered"),
                    ("r", "Rejected"),
                ],
                default="p",
                max_length=100,
            ),
        ),
    ]
