# Generated by Django 4.2.13 on 2024-07-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_orders_payment_alter_orders_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="orders",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[("p", "Pending"), ("c", "Completed"), ("r", "Rejected")],
                default="p",
                max_length=100,
            ),
        ),
    ]
