# Generated by Django 4.2.13 on 2024-07-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_cart_options_alter_contactus_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["category"]},
        ),
    ]
