# Generated by Django 4.2.13 on 2024-07-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(null=True, upload_to="user_image/"),
        ),
    ]
